## Noah Pishaki - Physics 490 - Assignment 5

In [197]:
import numpy as np

### 1.) Prove that left and right eigenvalues are equivalent.

Lets consider the Classic case:
The Right Eigenvalue.

Let A be the general form of a 2x2 Matrix

$
\boldsymbol{A}=
\left(\begin{array}{cc} 
a & b\\
c & d \\
\end{array}\right)
$

Let the eigenvalue be denoted by $\lambda_{R}$ and satisfy the equation

$A\vec{v_{R}} = \lambda_{R}\vec{v_{R}}$

Where, $\vec{v_{R}} $ is an arbitrary column vector.


Taking the characteristic polynomial $ det(A - \lambda_{R} I) = 0$

Where, I is the Identity Matrix

$
\boldsymbol{I}=
\left(\begin{array}{cc} 
1 & 0\\
0 & 1 \\
\end{array}\right)
$

Plugging this in we get

$
det(\left(\begin{array}{cc} 
a & b\\ 
c & d \\ 
\end{array}\right) - 
\lambda
\left(\begin{array}{cc} 
1 & 0\\ 
0 & 1 \\ 
\end{array}\right)) = 0
$

$
det(\left(\begin{array}{cc} 
a & b\\ 
c & d \\ 
\end{array}\right) - 
\left(\begin{array}{cc} 
\lambda & 0\\ 
0 & \lambda \\ 
\end{array}\right)) = 0
$

Which becomes,


$
det(\left(\begin{array}{cc} 
(a - \lambda) & b\\ 
c & (d - \lambda) \\ 
\end{array}\right)) = 0
$

And by *Laplace development*,

$ (a - \lambda)(d - \lambda) - bc = 0 $

$ ad - a\lambda - bc - d\lambda + \lambda^2 = 0 $

Meaning the Eigenvalues equal,

$ b = 0, d = a, \lambda = a $

Now lets consider the less common case:
The Left Eigenvalue.

Again, let A be the general form of a 2x2 Matrix

$
\boldsymbol{A}=
\left(\begin{array}{cc} 
a & b\\
c & d \\
\end{array}\right)
$

Let the eigenvalue be denoted by $\lambda_{L}$ and satisfy the equation

$\vec{v_{L}}A = \lambda_{L}\vec{v_{L}}$

Where, $\vec{v_{L}} $ is an arbitrary row vector.

This time we'll take the Transpose of both sides:

$(\vec{v_{L}}A)^T = \lambda_{L}\vec{v_{L}}^T$

$\vec{v_{L}}^T A^T = \lambda_{L}\vec{v_{L}}^T$

Simplifying,

$ (A^T -\lambda_{L} I)\vec{v_{L}}^T = \vec{0} $

Where, I is the Identity Matrix

$
\boldsymbol{I}=
\left(\begin{array}{cc} 
1 & 0\\
0 & 1 \\
\end{array}\right)
$

Again, taking the characteristic polynomial:

$ det(A^T -\lambda_{L} I) = 0 $

And

$
\boldsymbol{A^T}=
\left(\begin{array}{cc} 
a & c\\
b & d \\
\end{array}\right)
$


Plugging this in we get

$
det(\left(\begin{array}{cc} 
a & c\\ 
b & d \\ 
\end{array}\right) - 
\lambda
\left(\begin{array}{cc} 
1 & 0\\ 
0 & 1 \\ 
\end{array}\right)) = 0
$

$
det(\left(\begin{array}{cc} 
a & c\\ 
b & d \\ 
\end{array}\right) - 
\left(\begin{array}{cc} 
\lambda & 0\\ 
0 & \lambda \\ 
\end{array}\right)) = 0
$

Which becomes,


$
det(\left(\begin{array}{cc} 
(a - \lambda) & c\\ 
b & (d - \lambda) \\ 
\end{array}\right)) = 0
$

And similar to before, by *Laplace development*,

$ (a - \lambda)(d - \lambda) - cb = 0 $

$ ad - a\lambda - cb - d\lambda + \lambda^2 = 0 $

$ b = 0, d = a, \lambda = a $

Given *multiplication* follows the *commutative* property,


This proves the *Left* & *Right* Eigenvalues are Equalivalent values for any arbitrary real 2x2 matrix.

Alternatively this could be proven by showing the transpose operation can be pulled outside of the determinant

Showing $ det(A) = det(A^T) $ and building a diagonal matrix of the corresponding eigenvectors.

The above seems to be a more trivial approach.

### 2.) Compute the eigenvalues and eigenvectors (using np.linalg.eig()) of
$
\boldsymbol{A}=
\left(\begin{array}{cc} 
1 & 2 & 3\\
0 & 4 & 5 \\
0 & 0 & 4.001\\
\end{array}\right)
$

### We then introduce a perturbation, which adds 0.005 to the bottom left element. Please compute eigenvalues and eigenvectors for the perturbed matrix. 
### Please also calculate the condition number for each eigenvalues (using python).

In [198]:
A = np.array([[1,2,3], [0, 4, 5], [0, 0 , 4.001]], dtype=np.float64)

eig_val,eig_vec = np.linalg.eig(A) #first var returns eigenvalues in order of multiplicity, the second variable returns the normalized (unit"length") eigenvectors 

In [199]:
print('Eigenvalues of A:')
print(np.sort(eig_val))
print("")

print('Eigenvectors of A:')
print(np.sort(eig_vec))
print("")

print('======================')

for i in range(len(eig_val)):
    print("Eigenvector with corresponding Eigenvalue {}:".format(eig_val[i]))
    print((eig_vec[:,i]))
    print("")

print('======================')

print('Condition number of A:')
print(np.linalg.norm(A)*np.linalg.norm(np.linalg.inv(A)))

Eigenvalues of A:
[1.    4.    4.001]

Eigenvectors of A:
[[5.54687392e-01 5.54700196e-01 1.00000000e+00]
 [0.00000000e+00 8.32050294e-01 8.32058814e-01]
 [0.00000000e+00 0.00000000e+00 1.66411763e-04]]

Eigenvector with corresponding Eigenvalue 1.0:
[1. 0. 0.]

Eigenvector with corresponding Eigenvalue 4.0:
[0.5547002  0.83205029 0.        ]

Eigenvector with corresponding Eigenvalue 4.001:
[5.54687392e-01 8.32058814e-01 1.66411763e-04]

Condition number of A:
10.279768377267315


In [200]:
A[-1,0] = A[-1,0] +  0.005 #adding perturbation to the bottom left

eig_val_per, eig_vec_per = np.linalg.eig(A)

In [201]:
print('Eigenvalues of A + dA:')
print(np.sort(eig_val_per))
print("")

print('Eigenvectors of A + dA:')
print(np.sort(eig_vec_per))
print("")

print('======================')

for i in range(len(eig_val_per)):
    print("Eigenvector with corresponding Eigenvalue {}:".format(eig_val_per[i]))
    print((eig_vec_per[:,i]))
    print("")

print('======================')

print('Condition number of A + dA:')
print(np.linalg.norm(A)*np.linalg.norm(np.linalg.inv(A)))

Eigenvalues of A + dA:
[1.0005565  3.87111014 4.12933336]

Eigenvectors of A + dA:
[[-0.55629299 -0.55298164  0.99999475]
 [-0.83291484 -0.83071027  0.00277787]
 [-0.02154473 -0.00166641  0.02141403]]

Eigenvector with corresponding Eigenvalue 1.000556504040703:
[ 0.99999475  0.00277787 -0.00166641]

Eigenvector with corresponding Eigenvalue 4.129333359005014:
[-0.55298164 -0.83291484 -0.02154473]

Eigenvector with corresponding Eigenvalue 3.871110136954284:
[-0.55629299 -0.83071027  0.02141403]

Condition number of A + dA:
10.284595979995341
