## Noah Pishaki - Physics 490 - Assignment 6

In [363]:
import numpy as np
import scipy as sp
from scipy.linalg import lu, lu_solve, lu_factor

#### Problem 1.) Use LU decomposition to calculate the inverse of a matrix $\boldsymbol{A}$ and its determinant. Test your answers by comparing to the output of ```np.linalg.inv()``` and ```np.linalg.det().```

In [364]:
np.random.seed(1)

A = np.random.normal(size = (3, 3)) # 3x3 matrix of random numbers


Utilizing the Scipy-Module's Linalg Library.

In [365]:
P, L, U = sp.linalg.lu(A)

print("A:", A, '\n')
print("P:", P, '\n') # permutation matrix
print("L:", L, '\n') # lower triangular matrix
print("U:", U, '\n') # upper triangular matrix

A: [[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]] 

P: [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]] 

L: [[ 1.          0.          0.        ]
 [-0.61494807  1.          0.        ]
 [ 0.93095737  0.24388009  1.        ]] 

U: [[ 1.74481176 -0.7612069   0.3190391 ]
 [ 0.          0.39730492 -2.10534622]
 [ 0.          0.         -0.31173153]] 



Given a matrix **A** which can be decomposed into both lower and upper triangular matrices, in this case I'll be using a general/arbitrary (3x3),  we know from LU-Decomposition, **A** = **L** **U**. 

Now assume, $ A = \begin{bmatrix} a & b & c \\ d & e & f \\ g & h & i \end{bmatrix} $ where $L = \begin{bmatrix} 1 & 0 & 0 \\ \frac{x}{a} & 1 & f \\ \frac{g}{a} & \frac{h-\frac{bg}{a}}{e-\frac{bd}{a}} & 1 \end{bmatrix} $ is the *lower triangular* matrix and $ U = \begin{bmatrix} a & b & c \\ 0 & e - \frac{bd}{a} & f-\frac{cd}{a} \\ 0 & 0 & \frac{(h-\frac{bg}{a})(f-\frac{cd}{a})}{e-\frac{bd}{a}} \end{bmatrix}  $ is the *upper triangular* matrix.

We can then define **A** as,

$\begin{bmatrix} a & b & c \\ d & e & f \\ g & h & i \end{bmatrix} = \begin{bmatrix} 1 & 0 & 0 \\ \frac{x}{a} & 1 & f \\ \frac{g}{a} & \frac{h-\frac{bg}{a}}{e-\frac{bd}{a}} & 1 \end{bmatrix}\begin{bmatrix} a & b & c \\ 0 & e - \frac{bd}{a} & f-\frac{cd}{a} \\ 0 & 0 & \frac{(h-\frac{bg}{a})(f-\frac{cd}{a})}{e-\frac{bd}{a}} \end{bmatrix}  $



In [366]:
for i in range(L.shape[0]):
    L[i,i] = 0
    
LU = L + U
p = np.array([2,1,0])

#  Enter the vectors of knowns and permute them.
I1 = np.array([1,0,0]); I1 = p0 @ I1
I2 = np.array([0,1,0]); I2 = p0 @ I2
I3 = np.array([0,0,1]); I3 = p0 @ I3

#  Solve for the columns of our inverse matrix
b1 = lu_solve( (LU, p), I1)
b2 = lu_solve( (LU, p), I2)
b3 = lu_solve( (LU, p), I3)

# Make these explicitly column vectors
b1.shape = (3,1)
b2.shape = (3,1)
b3.shape = (3,1)

A_inv = np.hstack( (b1,b2,b3) )
print(A_inv)

[[ -6.82949293   2.76364776   8.63059432]
 [-16.99882312   6.66263299  19.92235287]
 [ -3.20788853   0.78234013   3.46750601]]


In [367]:
#  Is our answer the same as Numpy's built-in inv function?
A_num = np.linalg.inv(A)
print(A_num)

[[ -6.82949293   2.76364776   8.63059432]
 [-16.99882312   6.66263299  19.92235287]
 [ -3.20788853   0.78234013   3.46750601]]


In [368]:
# can't use np.array_equiv(A_num, A_inv) need to use np.allclose
print(np.allclose(A_num, A_inv))

True


If $ A = PLU $ we then know that $ (\det{A}) = (\det{P})(\det{L})(\det{U}) $ because the determinant of a triangular matrix is just the product of the diagonal since those are the eigenvalues.

In [369]:
detP = np.linalg.det(P)
detL = np.linalg.det(L)
detU = np.linalg.det(U)

detA = detP*detL*detU


print(detA, '\n')
print(round(np.linalg.det(A)), '\n')
print(np.allclose(detA, round(np.linalg.det(A))))

0.0 

0 

True


Had to round ```np.linalg.det(A)``` due to the numerical precision of numpy, Singular matrices are apparently not numerically well defined in terms of floating point values. 


```lu_factor``` has $ O(n^3) $ and ```lu_solve``` has $ O(n^2) $, while Solve has $ O(n^3) $ so theoretically we want to LU-Factor initial systems then use ```lu_solve```.